[package]
name = "serenity-utils"
version = "0.3.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "serenity_utils"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
derive_more = "0.99" # used in proc macro
parking_lot = "0.11" # used in proc macro
serde = "1"
serde_json = "1"
serenity = "0.9"
typemap = "0.3"

[dependencies.serenity-utils-derive]
path = "../serenity-utils-derive"

[dependencies.shlex] # used in proc macro
git = "https://github.com/fenhl/rust-shlex"

[dependencies.tokio]
version = "0.2" #TODO upgrade to 0.3 once supported by serenity
features = ["sync"]
